In [131]:
import numpy as np

CAPACITA_MAX=9
oggetti=[1,2,3,4]
weight=[2,7,6,4]
profit=[12.7,6.4,1.7,0.3]

v=np.ones((len(oggetti)+1,CAPACITA_MAX+1)).T
print(v.shape)
v[0,:]=0
v[:,0]=0

print(v)
print("\n")
for j in range(1,CAPACITA_MAX+1): 
    for i in range(1,len(oggetti)+1):
        ##v[k,j]=v[k-1,j] if weight[k]>j else max(v[k-1,j],v[k-1][j-weight[k]]+profit[k])
        #v[j][i]=2
        #k=i-1
        v[j][i]=v[j,i-1] if weight[i-1]>j else max(v[j,i-1],v[j-weight[i-1]][i-1]+profit[i-1])
        #print("Riga {0} Colonna {1}".format(j,i))
        print("Controllo --> V[{0}][{1}]".format(j,i))
        print("Oggetto:{0}\nPeso:{1}\nValore:{2}\nPesoMAXConsentito:{3}".format(i-1,weight[i-1],profit[i-1],j))
        if weight[i-1]>j:
            print("MAX v[{0}][{1}]".format(j,i-1))
            print(v[j][i-1])
        else:
            print("MAX tra v[{0}][{1}],v[{2}][{3}]+{4}".format(j,i-1,j-weight[i-1],i-1,profit[i-1]))
            print(v[j][i-1],v[j-weight[i-1]][i-1]+profit[i-1])
            #print("max{v[{0}][{1}],v[{2}][{3}]}".format(j,i-1,j-weight[i-1],i-1))
        print("\n")
        
print(v)
print(v[-1][-1])


(10, 5)
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]]


Controllo --> V[1][1]
Oggetto:0
Peso:2
Valore:12.7
PesoMAXConsentito:1
MAX v[1][0]
0.0


Controllo --> V[1][2]
Oggetto:1
Peso:7
Valore:6.4
PesoMAXConsentito:1
MAX v[1][1]
0.0


Controllo --> V[1][3]
Oggetto:2
Peso:6
Valore:1.7
PesoMAXConsentito:1
MAX v[1][2]
0.0


Controllo --> V[1][4]
Oggetto:3
Peso:4
Valore:0.3
PesoMAXConsentito:1
MAX v[1][3]
0.0


Controllo --> V[2][1]
Oggetto:0
Peso:2
Valore:12.7
PesoMAXConsentito:2
MAX tra v[2][0],v[0][0]+12.7
0.0 12.7


Controllo --> V[2][2]
Oggetto:1
Peso:7
Valore:6.4
PesoMAXConsentito:2
MAX v[2][1]
12.7


Controllo --> V[2][3]
Oggetto:2
Peso:6
Valore:1.7
PesoMAXConsentito:2
MAX v[2][2]
12.7


Controllo --> V[2][4]
Oggetto:3
Peso:4
Valore:0.3
PesoMAXConsentito:2
MAX v[2][3]
12.7


Controllo --> V[3][1]
Oggetto:0
Peso:2
Valore:12.7
PesoMAXConsentito:3
MAX tra